### ISSUE TITLE
How to see more details in structure view in ODD, like Unique, Missing, Min, Max, Median?

### ISSUE THREAD

**Issue by md2netamanda** [opendatadiscovery/odd-collector#128]
I am new in ODD. Actually, I created a server and discovery a postgres database, but when I am analyzing the structure I just see the column name and data type. I would like to see more details like Unique, Missing, Min, Max, Median. Could someone tell me how is it possible?

I watched this video https://www.youtube.com/watch?v=Y0aFqHd4h3k that in the 24 min they show us a view with this information.
![image](https://user-images.githubusercontent.com/118937040/205626017-2a43549f-1692-4744-9589-66bec221bcce.png)

Regards,
Amanda Lima

**Comment by DementevNikita** [comment]
hey @md2netamanda!

these details are fetched only if a data source **can provide them** (e.g. Hive or Glue (with certain limitations) precalculate statistics and provide an interface for us to fetch them). PostgreSQL doesn't do that and since we do not run analytical queries against real data, they are missing in your ODD Platform.

Please take a look at https://github.com/opendatadiscovery/odd-collector-profiler. This is a profiler which can inject such statistics for you. Unlike standard collectors, this one **is** running queries against **real data** and can inject statistics along with labels on columns and datasets. So it's kinda like separate collector that deals with statistics and data classification. The configuration though is quite similar to configuration of collectors, so there shouldn't be a problem. Nevertheless, please don't hesitate to create issues and ask questions is something breaks or remains unclear

**Comment by DementevNikita** [comment]
closing this since this ticket was a question. 

@md2netamanda please don't hesitate to recreate a ticket or create a new one if you have more questions
